[package]
name = "flexible-hyper-server-tls"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Choose between HTTP or HTTPS when using hyper"

[dependencies]
hyper = { version = "0.14.27", features = ["server"] }
tokio = { version = "1.29.1", features = ["net"] }
tokio-rustls = "0.24.1"
